/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ContestSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'deadline', 'description', 'id', 'imageUrl', 'organizer', 'status', 'title', 'updatedAt', 'weightJury', 'weightPublic'] as const
  $columns = ContestSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deadline: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare organizer: string | null
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weightJury: number | null
  @column()
  declare weightPublic: number | null
}

export class SubmissionSchema extends BaseModel {
  static $columns = ['contestId', 'createdAt', 'finalScore', 'id', 'imageUrl', 'participantName', 'title', 'updatedAt'] as const
  $columns = SubmissionSchema.$columns
  @column()
  declare contestId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare finalScore: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string
  @column()
  declare participantName: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VoteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'score', 'submissionId', 'type', 'userId', 'voterName'] as const
  $columns = VoteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare score: number | null
  @column()
  declare submissionId: number | null
  @column()
  declare type: string
  @column()
  declare userId: number | null
  @column()
  declare voterName: string | null
}
